server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

## server.port  当前的 Eureka service 端口
## eureka.client.register-with-eureka 是否注册当前的 Eureka service 服务作为客户端进行注册
## eureka.client.fetch-fegistry 是否获取其他 Eureka service 服务的数据
## eureka.client.service-url.defaultZone  注册中心的访问地址