server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instances:
      prefer-ip-address: true
zuul:
  routes:
    feign:
      path: /f/**
      service-id: feign
## zuul.routes.provider 给服务提供者  provider  设置映射
## zuul.routes.feign 给服务提供者  feign  设置映射