server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instances:
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true
## feign.hystrix.enabled   是否开起熔断机制